services:
  a:
    #image: ubuntu
    tty: true
    build: .
    networks:
      - l1
  r1:
    #image: ubuntu
    tty: true
    build: .
    networks:
      - l1
      - l2
  b:
    #image: ubuntu
    tty: true
    build: .
    networks:
      - l2

networks:
  l1:
    ipam:
      config:
        - subnet: 10.1.0.0/16
        - ip_range: 10.1.2.0/24
  
  l2:
    ipam:
      config:
        - subnet: 10.2.0.0/16
        - ip_range: 10.2.2.0/24