services:
  a:
    #image: ubuntu
    tty: true
    build: .
    networks:
      - l1
  r1:
    #image: ubuntu
    tty: true
    build: .
    networks:
      - l1
      - l2
  b:
    #image: ubuntu
    tty: true
    build: .
    networks:
      - l2

networks:
  l1:
    ipam:
      config:
        - subnet: 172.28.0.0/16
        - ip_range: 172.28.2.0/24
  
  l2:
    ipam:
      config:
        - subnet: 172.23.0.0/16
        - ip_range: 172.23.2.0/24