services:
  a:
    #image: ubuntu
    tty: true
    build: .
    networks:
      l1:
        ipv4_address: 172.28.2.3
  r1:
    #image: ubuntu
    tty: true
    build: .
    networks:
      l1:
        ipv4_address: 172.28.2.1
      l2:
        ipv4_address: 172.23.2.1
  b:
    #image: ubuntu
    tty: true
    build: .
    networks:
      l2:
        ipv4_address: 172.23.2.3

networks:
  l1:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.2.0/24
          gateway: 172.28.2.1
  
  l2:
    ipam:
      config:
        - subnet: 172.23.0.0/16
          ip_range: 172.23.2.0/24
          gateway: 172.23.2.1